### ISSUE TITLE
I can't get z-wave map

### ISSUE THREAD

**Issue by simulot** [abmantis/ozw-network-visualization-card#7]
I have used HACS for installing the OZW Network Visualization Card 

After reboot HA, clear the cache, I just have following error:
![image](https://user-images.githubusercontent.com/5980377/105148875-2c3a9b80-5b03-11eb-968a-b49f57c84bb7.png)

What I'm doing wrong?

**Comment by elgeniskogen** [comment]
I have the same problem

**Comment by mamoel666** [comment]
Add me to the list

**Comment by elgeniskogen** [comment]
Got it working :-) Go to Configuration -> Lovelace dashboards -> Resources -> add resource and then enter /hacsfiles/ozw-network-visualization-card/ozw-network-visualization-card.js as URL. 

The add this to a manual card:
type: 'custom:ozw-network-visualization-card'
integration: ozw

**Comment by simulot** [comment]
Indeed, this work. 
So, either the installation guide should be amended either the HACS installation should be fixed.

**Comment by jef-pearlman** [comment]
Just wanted to note that I've had this same problem and same solution with other HACS-installed cards, so i suspect the problem is either HACS or the Home Assistant resource system itself.  In several cases, the resource was already listed in Resources but removing it and re-adding it (just copy/pasting the URL back in) fixed it.

**Comment by abmantis** [comment]
Indeed, HACS should add the card automatically to the resources. If it is not doing that, please do report it in the HACS repo.
I'm not using HACS at the moment, so I'm not able to test it.
